# Generated by Django 6.0.3 on 2026-03-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_vip_attendees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='max_vip_attendees',
            field=models.PositiveIntegerField(default=0, help_text='Maximum VIP attendees (0 for unlimited)'),
        ),
        migrations.AddField(
            model_name='event',
            name='vip_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VIP ticket price (optional)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='early_bird_deadline',
            field=models.DateTimeField(blank=True, help_text='Early bird deadline', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='early_bird_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Early bird price (optional)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_attendees',
            field=models.PositiveIntegerField(help_text='Maximum total attendees'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Regular ticket price', max_digits=10),
        ),
    ]
