# Generated by Django 4.2.16 on 2026-03-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resale_marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="resalelisting",
            name="resale_mark_status_489c0c_idx",
        ),
        migrations.RemoveIndex(
            model_name="resalelisting",
            name="resale_mark_expires_382699_idx",
        ),
        migrations.RemoveIndex(
            model_name="resalelisting",
            name="resale_mark_seller__aa6758_idx",
        ),
    ]
