# Generated by Django 6.0.3 on 2026-03-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, help_text='Business name for sellers', max_length=200, null=True),
        ),
    ]
