# Generated by Django 6.0.3 on 2026-03-12 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_current_vip_attendees_event_max_vip_attendees_and_more"),
        ("merchandise", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchandiseitem",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merchandise_items",
                to="events.event",
            ),
        ),
    ]
